service: serverless-first-try
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-first-try
  stage: dev
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - s3:GetObject
        - s3:PutObject
        - ses:*
        - sns:SetSMSAttributes
        - sns:Publish
        - comprehend:*
      Resource: "*"
  apiKeys:
    - free:
      - MyFreeApiKey
    - paid:
      - MyPaidApiKey
  usagePlan:
    - free:
        quota:
          limit: 1000
          period: MONTH
        throttle:
          rateLimit: 5
          burstLimit: 20
    - paid:
        quota:
          limit: 10000
          period: MONTH
        throttle:
          rateLimit: 50
          burstLimit: 200

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  bucketName: serverlessuploadbucket

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{id}
          method: GET
          cors: true
          private: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{id}
          method: GET
          cors: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http:
          path: create-player-score/
          method: POST
          cors: true
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http:
          path: create-file/{fileName}
          method: POST
          cors: true
  getFile:
    handler: lambdas/endpoints/getFile.handler
    events:
      - http:
          path: get-file/{fileName}
          method: GET
          cors: true
  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - http:
          path: send-email
          method: POST
          cors: true
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
  analyse:
    handler: lambdas/endpoints/analyse.handler
    events:
      - http:
          path: analyse
          method: POST
          cors: true

resources:
  Resources:
    DemoBupcketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverlessuploadbucket
    MyDynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
    #MyAssumeRole:
    #  Type: AWS::IAM::Role
    #  Properties:
    #    RoleName: MyAssumeRole
    #    AssumeRolePolicyDocument:
    #      Version: "2012-10-17"
    #      Statement:
    #        - Effect: Allow
    #          Principal:
    #            Service:
    #              - lambda.amazonaws.com
    #              - apigateway.amazonaws.com
    #              - sns.amazonaws.com
    #          Action:
    #            - sts:AssumeRole
